<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>King Satan Tickets</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <a class="link-primary px-2 mx-5 fs-3" href="/kingsatan/">Tilastot</a>
            <a class="link-primary px-2 mx-5 fs-3" href="read">Lue liput</a>
            <a class="link-primary px-2 mx-5 fs-3" href="create">Luo uusi lippu</a>
            <a class="link-primary px-2 mx-5 fs-3" href="test">Testaa</a>
        </nav>
        <div class="content" style="margin-top: 20px;">
</body>
</html>